### ISSUE TITLE
[BUG] [Go Service] Get the supported locale list API is not working

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1759]
**Describe the bug**
The following API call receives gets a connection refused error: 
http://localhost:8093/i18n/api/v2/translation/products/CloudHealth/versions/1.0.0/localelist

**To Reproduce**
1. Unzip the attached bundle in local directory: [bundle.zip](https://github.com/vmware/singleton/files/9031163/bundle.zip)
2. Create a config/config.yaml file with the following change to the template:
```
LocalBundle:
  BasePath:  <path to directory in step 1>
```
3. Run the service locally.
4. Test the API using a Chrome and see "ERR_CONNECTION_REFUSED" or test using Postman and see "Could not get response
Error: socket hang up"
5. Also notice that the go service has crashed after the API call.

**Expected behavior**
HTTP 200 with the following json body:
`{"response":{"code":200,"message":"OK","serverTime":""},"signature":"","data":{"locales":["en","es","ja"],"version":"1.0.0","productName":"CloudHealth"}}
`

**Comment by jessiejuachon** [comment]
error log:
`2022-07-05T17:58:09.718Z	INFO	Start 'http' server listening on :8093
2022-07-05T18:00:31.130Z	INFO	Start a request	{"traceId": 39937785, "method": "GET", "ip": "::1", "path": "/i18n/api/v2/translation/products/CloudHealth/versions/1.0.0/localelist"}
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x10628df]

goroutine 66 [running]:
runtime.throw({0x1d9b6cf?, 0xd0?})
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:992 +0x71 fp=0xc000164ce8 sp=0xc000164cb8 pc=0x1034fd1
runtime.sigpanic()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/signal_unix.go:825 +0x305 fp=0xc000164d38 sp=0xc000164ce8 pc=0x104a705
aeshashbody()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc000164d40 sp=0xc000164d38 pc=0x10628df
runtime.mapiternext(0xc00019ee80)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/map.go:934 +0x2cb fp=0xc000164db0 sp=0xc000164d40 pc=0x1010feb
runtime.mapiterinit(0xc000164e48?, 0x100e7e5?, 0x4e455b8?)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/map.go:861 +0x228 fp=0xc000164dd0 sp=0xc000164db0 pc=0x1010cc8
reflect.mapiterinit(0x10105dd?, 0x1c5fc60?, 0xc0002124f8?)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/map.go:1373 +0x19 fp=0xc000164df8 sp=0xc000164dd0 pc=0x105ee19
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	/Users/jjuachon/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000847fb0, 0xc000010208, 0xc0001923c0)
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_map.go:291 +0x225 fp=0xc000164f68 sp=0xc000164df8 pc=0x14055e5
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0005ce7a0, 0xc0007e1b60, 0xc00019ee80?)
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:219 +0x82 fp=0xc000164fa0 sp=0xc000164f68 pc=0x13fdaa2
github.com/json-iterator/go.(*Stream).WriteVal(0xc0001923c0, {0x1caaaa0, 0xc0007e1b60})
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:98 +0x158 fp=0xc000165010 sp=0xc000164fa0 pc=0x13fcdb8
github.com/json-iterator/go.(*dynamicEncoder).Encode(0x1c8b960?, 0xc000212401?, 0xc0001923d8?)
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_dynamic.go:15 +0x39 fp=0xc000165040 sp=0xc000165010 pc=0x13ff479
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000847bf0, 0x1bd6709?, 0xc0001923c0)
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:110 +0x56 fp=0xc0001650b8 sp=0xc000165040 pc=0x1412d36
github.com/json-iterator/go.(*structEncoder).Encode(0xc000847cb0, 0x328b160?, 0xc0001923c0)
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_struct_encoder.go:158 +0x765 fp=0xc0001651a0 sp=0xc0001650b8 pc=0x1413745
github.com/json-iterator/go.(*Stream).WriteVal(0xc0001923c0, {0x1cd0f80, 0xc00000e228})
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:98 +0x158 fp=0xc000165210 sp=0xc0001651a0 pc=0x13fcdb8
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0002cd900, {0x1cd0f80, 0xc00000e228})
	/Users/jjuachon/go/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:299 +0xc9 fp=0xc0001652a8 sp=0xc000165210 pc=0x13f4069
github.com/json-iterator/go.API.Marshal-fm({0x1cd0f80?, 0xc00000e228?})
	<autogenerated>:1 +0x3e fp=0xc0001652d0 sp=0xc0001652a8 pc=0x141e8fe
github.com/gin-gonic/gin/render.WriteJSON({0x5f17908, 0xc0007e0b40}, {0x1cd0f80, 0xc00000e228})
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:72 +0x63 fp=0xc000165308 sp=0xc0001652d0 pc=0x15ba7c3
github.com/gin-gonic/gin/render.JSON.Render(...)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:58
github.com/gin-gonic/gin/render.(*JSON).Render(0xc000217e40?, {0x5f17908?, 0xc0007e0b40?})
	<autogenerated>:1 +0x45 fp=0xc000165338 sp=0xc000165308 pc=0x15bd185
github.com/gin-gonic/gin.(*Context).Render(0xc000150000, 0xc8, {0x3283238, 0xc000217e40})
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 +0xf8 fp=0xc000165368 sp=0xc000165338 pc=0x15c47d8
github.com/gin-gonic/gin.(*Context).JSON(...)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884
sgtnserver/api.HandleResponse(0x1caaaa0?, {0x1caaaa0?, 0xc0007e1b60?}, {0x0?, 0x0?})
	/Users/jjuachon/workspace-go/g11n-go-service2/api/utils.go:56 +0x3a5 fp=0xc000165500 sp=0xc000165368 pc=0x163cf05
sgtnserver/api/v2/translation.GetAvailableLocales(0xc000150000)
	/Users/jjuachon/workspace-go/g11n-go-service2/api/v2/translation/handler_trans.go:75 +0x2b8 fp=0xc000165598 sp=0xc000165500 pc=0x1ad8f18
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
sgtnserver/api.RecoveryWithZap.func1(0xc000150000)
	/Users/jjuachon/workspace-go/g11n-go-service2/api/middlewares.go:137 +0x7b fp=0xc0001655e0 sp=0xc000165598 pc=0x163aadb
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
sgtnserver/api.GinZap.func1(0xc000150000)
	/Users/jjuachon/workspace-go/g11n-go-service2/api/middlewares.go:70 +0x7e2 fp=0xc000165888 sp=0xc0001655e0 pc=0x163a3a2
github.com/gin-gonic/gin.(*Context).Next(...)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0002bc000, 0xc000150000)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x6c5 fp=0xc000165a58 sp=0xc000165888 pc=0x15ca885
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0002bc000, {0x3284ef0?, 0xc0008641c0}, 0xc0000f2100)
	/Users/jjuachon/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x1b4 fp=0xc000165a98 sp=0xc000165a58 pc=0x15c9ff4
net/http.serverHandler.ServeHTTP({0xc0007e0060?}, {0x3284ef0, 0xc0008641c0}, 0xc0000f2100)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 +0x43b fp=0xc000165b58 sp=0xc000165a98 pc=0x12c947b
net/http.(*conn).serve(0xc00021a000, {0x3285b98, 0xc0008287b0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 +0x5d7 fp=0xc000165fb8 sp=0xc000165b58 pc=0x12c4477
net/http.(*Server).Serve.func3()
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x2e fp=0xc000165fe0 sp=0xc000165fb8 pc=0x12c9dce
runtime.goexit()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000165fe8 sp=0xc000165fe0 pc=0x1065501
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db

goroutine 1 [chan receive, 2 minutes]:
sgtnserver/api.ShutdownServer()
	/Users/jjuachon/workspace-go/g11n-go-service2/api/server.go:140 +0x92
sgtnserver/api.StartServer()
	/Users/jjuachon/workspace-go/g11n-go-service2/api/server.go:127 +0x178
main.main()
	/Users/jjuachon/workspace-go/g11n-go-service2/cmd/singleton/main.go:23 +0x57

goroutine 7 [select, 2 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0004faf60)
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0x91
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x156

goroutine 20 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00010e1e0)
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0xa8
created by github.com/dgraph-io/ristretto.NewCache
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x56a

goroutine 10 [select, 2 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc000012c00)
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/policy.go:96 +0x91
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/policy.go:80 +0x156

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00010e360)
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/cache.go:314 +0xa8
created by github.com/dgraph-io/ristretto.NewCache
	/Users/jjuachon/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.3/cache.go:162 +0x56a

goroutine 50 [syscall, 2 minutes]:
os/signal.signal_recv()
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/sigqueue.go:148 +0x28
os/signal.loop()
	/usr/local/Cellar/go/1.18.3/libexec/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/Cellar/go/1.18.3/libexec/src/os/signal/signal.go:151 +0x2a

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x5f17738, 0x72)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0003aa180?, 0x4?, 0x0)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc0003aa180)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc0003aa180)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc00000e210)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc00000e210)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc0008640e0, {0x3284ce0, 0xc00000e210})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc0008640e0)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:2968 +0x7d
sgtnserver/api.StartServer.func1()
	/Users/jjuachon/workspace-go/g11n-go-service2/api/server.go:108 +0x145
created by sgtnserver/api.StartServer
	/Users/jjuachon/workspace-go/g11n-go-service2/api/server.go:105 +0x345

goroutine 67 [IO wait]:
internal/poll.runtime_pollWait(0x5f17558, 0x72)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0003aa280?, 0xc00039d000?, 0x0)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0003aa280, {0xc00039d000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003aa280, {0xc00039d000?, 0xc0006876a0?, 0x12be0a5?})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000198018, {0xc00039d000?, 0x203000?, 0x203000?})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc000828f30, {0xc00039d000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc000680240)
	/usr/local/Cellar/go/1.18.3/libexec/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc000680240, 0x0?)
	/usr/local/Cellar/go/1.18.3/libexec/src/bufio/bufio.go:371 +0x2f
bufio.(*Reader).ReadLine(0xc000680240)
	/usr/local/Cellar/go/1.18.3/libexec/src/bufio/bufio.go:400 +0x27
net/textproto.(*Reader).readLineSlice(0xc000828f90)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc000198018?)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc00021a140, {0x3285af0, 0xc00004a340})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:988 +0x24a
net/http.(*conn).serve(0xc00021a140, {0x3285b98, 0xc0008287b0})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:1891 +0x32b
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:3071 +0x4db

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x5f17648, 0x72)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0003aa200?, 0xc0007e0071?, 0x0)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0003aa200, {0xc0007e0071, 0x1, 0x1})
	/usr/local/Cellar/go/1.18.3/libexec/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0003aa200, {0xc0007e0071?, 0x0?, 0x0?})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000198010, {0xc0007e0071?, 0x0?, 0x0?})
	/usr/local/Cellar/go/1.18.3/libexec/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc0007e0060)
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:672 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/usr/local/Cellar/go/1.18.3/libexec/src/net/http/server.go:668 +0xca`

**Comment by jessiejuachon** [comment]
Per @lyiyu66 's investigation:

> Go 1.16.15: service can run and work normally.
Go 1.18.2: service can start but it will be crashed once request is sent. Your mentioned issues can be reproducible on the environment.
