### ISSUE TITLE
[BUG] [Python client]import custom logger instance cause execute error.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1788]
**Describe the bug**
import custom logger instance cause execute error.

**To Reproduce**
1. import custom logger instance
2. SingletonRelease.set_logger(logger)
3. run and see error.
`Traceback (most recent call last):
  File "C:\Users\ducker\PycharmProjects\projects\singleton\test\icu_tester\test_l2_icu.py", line 46, in <module>
    rel.set_logger(logger)
  File "C:\Users\ducker\PycharmProjects\projects\singleton\sgtn4python\sgtnclient\sgtn_client.py", line 682, in set_logger
    self.log('')
  File "C:\Users\ducker\PycharmProjects\projects\singleton\sgtn4python\sgtnclient\sgtn_client.py", line 687, in log
    SysUtil.log(self.logger, text, log_type)
  File "C:\Users\ducker\PycharmProjects\projects\singleton\sgtn4python\sgtnclient\sgtn_util.py", line 299, in log
    release_logger.log(text, log_type)
  File "C:\Program Files\Python39\lib\logging\__init__.py", line 1508, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer`

**Screenshots**
If applicable, add screenshots to help you explain your issue
![image](https://user-images.githubusercontent.com/64178605/178682982-eb9235a5-e657-44f8-9055-d1c4c9f5f0d1.png)

**Additional context**
python logging.log(level:int, msg:str)
but singleton logger incompatible.
@classmethod
def log(cls, release_logger, text, log_type=LOG_TYPE_INFO):
    if release_logger:
        release_logger.log(text, log_type)

**Comment by dleng-vmware** [comment]
The developer confirmed that this was the way the feature was designed
