### ISSUE TITLE
[BUG] [JAVA Client] Internal Server Error path: /i18n/pattern?locale=NSFTW

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2256]
Get `Internal Server Error` with following path in brobwer <IP>/i18n/pattern?locale=NSFTW

We should have any path with response "Internal Server Error.

**Comment by huihuiw01** [comment]
The specified error is:
java.lang.ClassCastException: java.lang.String cannot be cast to org.json.simple.JSONObject
	at com.vmware.vipclient.i18n.l2.dao.impl.RemotePatternDao.getCategoriesFromResponse(RemotePatternDao.java:52)
	at com.vmware.vipclient.i18n.l2.dao.impl.RemotePatternDao.getPatternsByLocale(RemotePatternDao.java:36)
	at com.vmware.vipclient.i18n.l2.service.impl.PatternService.getPatternsFromRemote(PatternService.java:40)
	at com.vmware.vipclient.i18n.l2.action.BaseFormatAction.getPatternsFromBundle(BaseFormatAction.java:71)
	at com.vmware.vipclient.i18n.l2.action.BaseFormatAction.getPatterns(BaseFormatAction.java:48)
	at com.vmware.vip.i18n.VIPPatternFilterTest.doFilter(VIPPatternFilterTest.java:39)
	at com.vmware.vip.i18n.VIPPatternFilterTest.testDoFilter(VIPPatternFilterTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
[com.vmware.vipclient.i18n.l2.action.BaseFormatAction]Got pattern from local bundle!
Can't find file /Users/vmware/Documents/whh/GitRepository/VIP/g11n-service/g11n-ws/clients/java/vIPJavaClient/out/test/classes/level2/en/patterns.json
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at com.vmware.vipclient.i18n.util.PatternBundleUtil.readJSONFile(PatternBundleUtil.java:61)
	at com.vmware.vipclient.i18n.l2.dao.impl.LocalPatternDao.getPatternsByLocale(LocalPatternDao.java:19)
	at com.vmware.vipclient.i18n.l2.service.impl.PatternService.getPatternsFromLocal(PatternService.java:44)
	at com.vmware.vipclient.i18n.l2.action.BaseFormatAction.getPatternsFromBundle(BaseFormatAction.java:67)
	at com.vmware.vipclient.i18n.l2.action.BaseFormatAction.getPatterns(BaseFormatAction.java:50)
	at com.vmware.vip.i18n.VIPPatternFilterTest.doFilter(VIPPatternFilterTest.java:39)
	at com.vmware.vip.i18n.VIPPatternFilterTest.testDoFilter(VIPPatternFilterTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by huihuiw01** [comment]
The reason of above error is the locale is invalid and Singleton service return 400 and the value of 'data' node is a error message instead of correct json data. Currently in code we use response code before handle the response data, when the code is 200 the structure of 'data' node must be json, so above error won't appear.
