### ISSUE TITLE
[BUG] [Singleton Serive lite build] failed to start build

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#279]
**Describe the bug**
Singleton Service provides a new kind of build - lightweight version.
But failed to start the build with the error message:
```
Exception in thread "main" java.lang.ClassNotFoundException: com.vmware.vip.BootApplication
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**To Reproduce**
1. To generate the Singleton service build based on the latest master code
2. Find the lite version build in `singleton\g11n-ws\vip-manager-lite-i18n\build\libs\vip-manager-lite-i18n-0.1.0-boot.jar`
3. To start the build with command: java -jar vip-manager-lite-i18n-0.1.0-boot.jar
4. See error above

**Expected behavior**
To start Singleton Service lite build successfully.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by nannany00** [comment]
It's fixed after #281 merged. Close it.
